### ISSUE TITLE
pthreads may not work under Windows

### ISSUE THREAD

**Issue by msuchard** [OHDSI/LocalControl#1]
I don't think `pthreads` are natively supported on Win-boxes.  The package `RcppParallel` provides pretty good cross-platform compatible threading for fork-join patterns.

**Comment by schuemie** [comment]
Hmm, oddly enough I seem to be able to run the package just fine, despite our previous bad experiences with `pthreads`.

**Comment by msuchard** [comment]
That is interesting.  Perhaps you have a `pthreads` library installed somewhere?  But, you have to compile the library using `Rtools`, no?   It looks like CRAN won't compile this package: https://cran.r-project.org/web/packages/LocalControl/index.html .

On the other hand, we have already pretty much made `Rtools` an OHDSI-stack dependency.  But, we are still left with the question: for where are your `pthreads` coming?

**Comment by msuchard** [comment]
I'd still recommend:
1. `RcppParallel` (which can work pre-`c++11`), or
2. Plain old `c++11` threading (which is easy to use).

Re: `pthreads` on Windows, see: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Using-pthreads

**Comment by ChristopheLambert** [comment]
The compilation environment provided by rstudio under Windows enables compilation of this package. It also complies with CRAN standards. CRAN has just built a Windows binary, so if you are just trying to run the package, you should be able to run the following under R to install:
`install.packages("LocalControl")`

**Comment by ChristopheLambert** [comment]
Actually, wait 24 hours -- CRAN notified us that they completed the windows binary and will post soon.

**Comment by msuchard** [comment]
Doh ... looks like times are a-changing. 👍
