### ISSUE TITLE
Request: please add a vignette

### ISSUE THREAD

**Issue by schuemie** [OHDSI/LocalControl#3]
There is already a lot of wonderful documentation of each of the functions, but users may find a vignette helpful to understand how the functions would be used together, for example by applying them to some of the data included in the package. 

See [this vignette in EmpiricalCalbration](https://raw.githubusercontent.com/OHDSI/EmpiricalCalibration/master/inst/doc/EmpiricalPCalibrationVignette.pdf) for an example.

**Comment by ChristopheLambert** [comment]
We are preparing to submit a vignette to the Journal of Statistical Software, and then will post here. We wanted to have the code up and deposited in CRAN so we can point to it as we submit our paper.

**Comment by alondhe** [comment]
Hi @ChristopheLambert -- just wondering if you have that vignette available. Even if it's a draft, I'd be interested in reading it, as I am trying to better understand how to use this package.

**Comment by ChristopheLambert** [comment]
Hi Ajit. We do. Will post soon. I will email a copy to you separately.

**Comment by ChristopheLambert** [comment]
A vignette has been added.
